name: GuiTest
main: xyz.michelepip.guitest.GuiTest
version: 1.0-SNAPSHOT
api-version: 1.20
description: GuiTest
author: Michele

commands:
  helloworld:
    description: 'HelloWorld'
  refreshfilter:
    description: 'Refresh Chat Filter'
  warn:
    description: 'Warn player'
  iftest:
    description: 'Test IF'